# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: /:title.html
timezone: America/Sao_Paulo

# Setup
title: 常阳时光(syn)
description: '常阳时光 Github 同步'
baseurl:     ''
url:         'http://syn.cyhour.com'

author:
  name: '老杨'
  url: http://syn.cyhour.com
  email: i@cyhour.com

paginate: 8

# Custom vars
show_related_posts: true

google_analytics: UA-48556550-3
comments: true