# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: /:title.html
timezone: Asia/Hong_Kong

# Setup
title: 常阳时光(syn)
description: 'CYHOUR.COM Github 同步更新站'
baseurl:     ''
url:         'http://syn.cyhour.com'

author:
  name: '老杨'
  url: http://syn.cyhour.com
  email: i@cyhour.com

paginate: 8

# Custom vars
show_related_posts: true

google_analytics: UA-48556550-3
comments: true